### PR TITLE
replace fromId by talkerId, toId by listenerId

### PR DESCRIPTION
**Pull request by fabian4**
fix https://github.com/wechaty/puppet/issues/187

### CODE REVIEW

**Review by huan — APPROVED** [review]
LGTM & Good job!

**Review by huan — APPROVED** [review]
LGTM & Good job!

**Comment by huan** [comment]
BTW: We should also bump the version of the walnut to v1.18 so that it can be sync with the Wechaty Puppet version.

**Comment by fabian4** [comment]
> 

ok

**Review by su-chang — APPROVED** [review]

**Pull request merged**
