### PR TITLE
fix badge and update readme

### PR DESCRIPTION
**Pull request by fabian4**

### CODE REVIEW

**Review by su-chang — APPROVED** [review]
LGTM

**Review by IronConrad — COMMENTED** [review]
Thanks for your hard work~

**Review by IronConrad — APPROVED** [review]

**Comment by fabian4** [comment]
@huan ping

**Review by huan — APPROVED** [review]
LGTM

Thank you very much for the improvements!

**Comment by fabian4** [comment]
@lijiarui ping

**Review by lijiarui — APPROVED** [review]
Good job!

**Pull request merged**
